### ISSUE TITLE
Tópico em aberto

### ISSUE THREAD

**Issue by marceloangomes** [cami-la/curso-dio-dominando-ides-java#1]
**Configurando o ícone do Eclipse IDE no Dock**

Me parece que este tópico está solto no conteúdo de linux

**Comment by cami-la** [comment]
Oi Marcelo, bem observado!

Às vezes quando se faz o download e instalação do Eclipse, o ícone não aparece no dock. Quando isso acontece, somos obrigados a iniciar o Eclipse por linha de comando e não é nada funcional. kk
Aí para consertar isso, é preciso alterar o caminho de um arquivo de configuração.
Acabei ficando sem tempo de criar esse script, mas vou fazer sim.

Parabéns pela dedicação, viu? Sinal que você está acompanhando o curso direitinho. :))

**Comment by marceloangomes** [comment]
Obrigado Camila !
