### ISSUE TITLE
Correção no item requisitos

### ISSUE THREAD

**Issue by waldirmor** [cami-la/curso-dio-dominando-ides-java#4]
Oi Camila tudo bem? Parabéns pela iniciativa. 
Uma dúvida. 
Nos pré-requisitos consta criação de uma conta no GITHUB, mas no decorrer do curso o que consta no final é a instalação do GIT e não GITHUB.. 
É só uma dúvida pois sou iniciante em GITHUB e programação
Obrigado

**Comment by cami-la** [comment]
Oi @waldirmor, tudo sim! E contigo? :smiley: 

Seja bem-vindo ao mundo da programação! E obrigada pelo feedback! :heart: 
Antes de mais nada, te sugiro esse [Bootcamp](https://web.digitalinnovation.one/track/html-web-developer?tab=path). Tenho certeza que irá te ajudar bastante!

Sobre sua dúvida:
Pedi como pré-requisito para o aluno começar o curso "Dominando IDEs Java" , ter uma conta no **GitHub** porque considero um cadastro bem basiquinho.

**Git** e **GitHub** são coisa diferentes.
**Git** é a ferramenta para versionar projetos X **GitHub** é a plataforma/site onde vamos subir esses projetos versionados.

O **Git** eu ensino como instalar na nossa máquina, pois será com ele que nós vamos fazer o VERSIONAMENTO do nossos projetos para o GitHub. Então, o **Git precisamos instalar**, já o **GitHub não precisamos instalar**. (Mas existe esta opção)

[O versionamento é o gerenciamento de versões diferentes de um documento de texto qualquer. Perceba que não precisa ser código. O versionamento é controlado pelo o que chamamos de sistema de controle de versões.](https://medium.com/biblioteca-dos-devs/como-versionar-utilizando-o-git-1f5d8fe2afcd)

Se ficou confusa minha explicação, aqui na [Digital Innovation One](https://web.digitalinnovation.one/browse?filter=Git) temos cusos perfeitos que falam sobre Git, GitHub e uma outra opção de plataforma GitLab.

Sinta-se à vontade para compartilhar suas dúvidas comigo. Até logo.

**Comment by waldirmor** [comment]
Bom dia Camila.. Muito obrigado pela resposta.. Já comecei o Bootcamp.. Estamos juntos..  Abração

**Comment by waldirmor** [comment]
Boa tarde Camila . 
Pelo que constatei são dois gigantes diferentes
Git  - Opensource criado pelo Linus Torvalds  CLI - command line interface
Gihub - De atual propriedade da Microsoft . foi adquirido através de uma compra pela mesma.. GUI graphic user interface
Pelo que entendi o Git não tem muito interface visual.. Já o Github usa mais interface visual
De qualquer forma continuo com meus estudos aqui, ainda tenho que aprender muito.. rs
por hora estou criando um user no Git... 
Abração . bons estudos pra vc tbm

**Comment by cami-la** [comment]
Muito bem! É isso mesmo, está no caminho certo. Já está entendendo a diferença entre Git x GitHub 🔝
Feliz em saber que você está progredindo nos estudos. 
Precisando estou à disposição 😃
