### ISSUE TITLE
Acesso Negado ao GitHub pelo Intellij

### ISSUE THREAD

**Issue by adm-rodrigoribeiro** [cami-la/curso-dio-dominando-ides-java#9]
Assistindo a aula sobre versionamento no Intellij tive um problema de acesso negado ao GitHub como mostra o print abaixo:
![ERRO INTELLIJ](https://user-images.githubusercontent.com/91813717/136643861-df4b8141-d058-459f-8572-bbdd15ce2793.JPG)

**Comment by cami-la** [comment]
> Assistindo a aula sobre versionamento no Intellij tive um problema de acesso negado ao GitHub como mostra o print abaixo: ![ERRO INTELLIJ](https://user-images.githubusercontent.com/91813717/136643861-df4b8141-d058-459f-8572-bbdd15ce2793.JPG)

No caso Rodrigo, você conseguiu fazer o Access Token, né?
Mas no IntelliJ não está pedindo o Access Token e já está exibindo essa mensagem? É isso?

Se sim, tenho 3 possíveis soluções:
1. Me parece que você está pegando a URL com o git@github.com... do repositório lá no GitHub que é referente ao SSH. Se sim, pega a URL HTTPS que começa com https://. Se não, vamos para opção 2.
2. Fazer o primeiro push pelo terminal com o Access Token ([[ERRO SOLUCIONADO] Como acessar o GitHub com um PERSONAL ACCESS TOKEN Out/2021](https://www.youtube.com/watch?v=wcIm916zk9w&lc=UgwDmJkoCf5M9Pf66ll4AaABAg)). Depois disso, o diretório fica versionado e você tenta usar no IntelliJ. Caso não funcione, vamos para opção 3.
3. Registrar uma key SSH que vou mostrar como faz amanhã no YouTube. ((:

**Comment by adm-rodrigoribeiro** [comment]
Realmente acabei usando o SSH ao invés do HTML.

Agora deu certo!

Obrigado!

**Comment by cami-la** [comment]
> Realmente acabei usando o SSH ao invés do HTML.
> 
> Agora deu certo!
> 
> Obrigado!



> Realmente acabei usando o SSH ao invés do HTML.
> 
> Agora deu certo!
> 
> Obrigado!

Por nada! Fico à disposição.
